name: CivClaims
version: '0.1.0'
main: net.meetlounge.civclaims.CivClaims
api-version: '1.21.10'
author: Aron
commands:
  city:
    description: Verwaltet Städte und Claims.
    usage: /city help
permissions:
  civclaims.admin:
    description: Erlaubt Admin-Befehle.
    default: op
